name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    
    env:
      API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
      DATASET_ID: ${{ secrets.DATASET_ID }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      WORKFLOW_ID: ${{ secrets.WORKFLOW_ID }}
      HOST_URL: app.indico.io
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      - name: Run formatter
        run: |
          black indico_toolkit

      - name: Run tests
        run: |
          pytest