name: Solutions Toolkit Pytest Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    
    env:
      USING_COVERAGE: "3.9"
      API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
      DATASET_ID: ${{ secrets.DATASET_ID }}
      MODEL_NAME: ${{ secrets.MODEL_NAME }}
      WORKFLOW_ID: ${{ secrets.WORKFLOW_ID }}
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: $

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      
      - name: Run formatter
        run: |
          black solutions_toolkit

      - name: Run tests
        run: |
          pytest